version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/HouzuoGuo/laitos
    parallelism: 2
    steps:
      - checkout
      - run: go test -v -cover ./...
      - run: go build