version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/HouzuoGuo/laitos
    parallelism: 1
    steps:
      - checkout
      - run: go build
      - run: go vet ./...
      - run: go test -v -cover ./...
